version: '3.9'
services:
  api:
    container_name: api
    image: api
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: yarn run start:dev
    env_file:
      - .env
    networks: 
      - main
    depends_on:
      - mongo
      - node
    restart: unless-stopped

  mongo:
    container_name: mongo
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
       - main
       - mongo
    volumes:
      - database:/data/mongo

  mongo_test:
    container_name: mongo_test
    image: mongo:latest
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${TEST_MONGO_PORT}:${MONGO_PORT}
    networks:
       - main
       - mongo
    volumes:
      - database:/data/mongo_test

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_ADMIN_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_ADMIN_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_URI}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
    links:
     - mongo
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - mongo
    depends_on:
      - mongo
    ports:
      - 8081:8081
  
  node:
    image: trufflesuite/ganache-cli:latest
    container_name: node
    ports:
      - "8545:8545"
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --debug
      - --defaultBalanceEther
      - '100000'
    networks:
      - main

volumes:
  database:

networks:
  main:
  mongo: